micronaut-projects/micronaut-kubernetes

kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/discovery/KubernetesDiscoveryClient.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/discovery/KubernetesDiscoveryClientEnabledSpec.groovy
See: https://github.com/micronaut-projects/micronaut-core/pull/1500
=> Replace Env. variable KubernetesDiscoveryClient

build.gradle
=> Use new Gradle build plugins

.github/workflows/gradle.yml
This should have gone also with #272
=> Only publish snapshot docs from one job

kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/discovery/provider/KubernetesServiceInstanceEndpointProvider.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/discovery/provider/KubernetesServiceInstanceEndpointProviderSpec.groovy, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/discovery/provider/KubernetesServiceInstanceServiceProviderSpec.groovy
Fixes #283 
This was partially fixed by https://github.com/micronaut-projects/micronaut-kubernetes/pull/291, this PR introduces test and fixes a case with NoSuchElement exception.
=> fix: NPE when discovered endpoint is missing addresses

gradle.properties, kubernetes-discovery-client/build.gradle
- setup githubCoreBranch to 3.0.x
- set project version to 3.0.0-SNAPSHOT
=> build: bump up to Micronaut 3.0.0-M5

kubernetes-client/src/main/java/io/micronaut/kubernetes/client/ApiClientConfiguration.java, test-utils/src/main/groovy/io/micronaut/kubernetes/test/KubernetesOperations.groovy
=> fix: Use immutable configuration properties for client

kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/KubernetesConfiguration.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigurationClient.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/util/KubernetesUtils.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/configuration/KubernetesConfigurationClientLabelsSpec.groovy, src/main/docs/guide/config-client.adoc
This is a possible solution to resolve #323
=> Fail fast property for missing pod labels

examples/micronaut-client/src/test/groovy/micronaut/client/HelloControllerSpec.groovy, examples/micronaut-service/src/main/resources/bootstrap.yml, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/KubernetesConfiguration.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcherCondition.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigurationClient.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/util/KubernetesUtils.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcherSpec.groovy, src/main/docs/guide/config-client.adoc, test-utils/src/main/groovy/io/micronaut/kubernetes/test/KubernetesSpecification.groovy, test-utils/src/main/resources/k8s/example-service-deployment.yml, test-utils/src/main/resources/k8s/mounted.yml
=> feat: Add support to load configmaps when mounted as a volume

examples/micronaut-client/src/test/groovy/micronaut/client/HelloControllerSpec.groovy, kubernetes-discovery-client/build.gradle, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/ConfigMapLabelSupplier.java, kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcherSpec.groovy
Depends on #347 that must go first.
=> feature: Informer configmap discovery client

kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java, kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcherSpec.groovy, kubernetes-informer/src/main/java/io/micronaut/kubernetes/client/informer/DefaultSharedIndexInformerFactory.java, kubernetes-informer/src/test/groovy/io/micronaut/kubernetes/client/informer/DuplicitConfigMapInformerSpec.groovy, kubernetes-informer/src/test/java/io/micronaut/kubernetes/client/informer/DuplicitConfigMapInformer.java
=> Fix issues #392 and #391 

kubernetes-bom/build.gradle, settings.gradle
=> build: add kubernetes bom

test-utils/build.gradle
Reverts micronaut-projects/micronaut-kubernetes#422
=> Revert "build: bump kubernetes-client from 5.11.1 to 5.12.0"

kubernetes-bom/build.gradle
=> Fix: BOM contains invalid entry

.github/workflows/graalvm.yml, .github/workflows/gradle.yml
Not sure why the template project hasn't updated it
=> ci: update mikepenz/action-junit-report

examples/micronaut-client/src/main/java/micronaut/client/LegacyEnvEndpointFilter.java, examples/micronaut-client/src/main/resources/application.yml, examples/micronaut-kubernetes-client/src/main/java/micronaut/service/LegacyEnvEndpointFilter.java, examples/micronaut-kubernetes-client/src/main/resources/application.yml, examples/micronaut-kubernetes-informer/src/main/java/micronaut/informer/LegacyEnvEndpointFilter.java, examples/micronaut-kubernetes-informer/src/main/resources/application.yml, examples/micronaut-kubernetes-operator/src/main/java/micronaut/operator/LegacyEnvEndpointFilter.java, examples/micronaut-kubernetes-operator/src/main/resources/application.yml, examples/micronaut-service/src/main/resources/application.yml, gradle.properties
- Update Groovy to 3.0.10
- Update Micronaut to 3.3.4
- Update version to 3.4.0-SNAPSHOT
- Update core branch to 3.4.x
=> build: Readiness for Micronaut 3.4.0

kubernetes-client-reactor/build.gradle
reactor-core is api from micronaut-reactor:
https://github.com/micronaut-projects/micronaut-reactor/blob/master/reactor/build.gradle#L9
=> build: remove reactor version

kubernetes-client-reactor/build.gradle, kubernetes-client-rxjava2/build.gradle, kubernetes-client-rxjava3/build.gradle, kubernetes-client/build.gradle, kubernetes-discovery-client/build.gradle, kubernetes-informer/build.gradle, kubernetes-operator/build.gradle
It is applied by id io.micronaut.build.internal.module
=> build: ann processor micronaut-docs-asciidoc-config-props

kubernetes-client/build.gradle, kubernetes-discovery-client/build.gradle, kubernetes-informer/build.gradle, kubernetes-operator/build.gradle
It is applied by `io.micronaut.build.internal.module`
=> build: delete ann processor inject-java

kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/ConfigMapLabelSupplier.java
=> Fix issue #479

.github/actions/graalvm-build/action.yml, .github/actions/gradle-build/action.yml, .github/actions/gradle-post-build/action.yml
=> ci: add missing inputs to github actions

.github/actions/graalvm-build/action.yml, .github/actions/graalvm-post-build/action.yml, .github/actions/graalvm-pre-build/action.yml, .github/actions/gradle-build/action.yml, .github/actions/gradle-post-build/action.yml, .github/actions/gradle-pre-build/action.yml, .github/actions/gradle-publish-github-pages/README.md, .github/actions/gradle-publish-github-pages/action.yml, .github/actions/gradle-publish-sona-type/README.md, .github/actions/gradle-publish-sona-type/action.yml, .github/workflows/graalvm.yml, .github/workflows/gradle.yml
Changes:
- Remove OCI runners
- Adds `gradle-publish-sona-type` action
- Adds `gradle-publish-github-pages` action
Both actions are extracted from `gradle-post-build` action. It makes more customisable with `env` and `if` blocks.
=> Remove OCI runners

settings.gradle, src/main/docs/guide/config-client.adoc, src/main/docs/guide/introduction.adoc, src/main/docs/guide/kubernetes-client.adoc, src/main/docs/guide/kubernetes-operator.adoc, src/main/docs/guide/service-discovery.adoc
=> Migrate to new configuration asciidoc macro and build plugin to 5.4.4
